---
- hosts: all
  become: yes
  tasks:

    ########################################
    # STEP 4 — ADD USERS + REGISTER SSH KEYS
    ########################################
    - name: Ensure users exist
      ansible.builtin.user:
        name: "{{ item }}"
        state: present
        shell: /bin/bash
      loop:
        - itsnotelena
        - SarinhaCortez
        - BernaJojo
        - WotsM

    - name: Set authorized keys from GitHub
      ansible.posix.authorized_key:
        user: "{{ item }}"
        state: present
        key: "https://github.com/{{ item }}.keys"
      loop:
        - itsnotelena
        - SarinhaCortez
        - BernaJojo
        - WotsM


    ###############################
    # STEP 5 — DISABLE SWAP
    ###############################
    - name: Disable SWAP
      ansible.builtin.command: swapoff -a

    - name: Remove swap entry in /etc/fstab
      ansible.builtin.lineinfile:
        path: /etc/fstab
        regexp: '\bswap\b'
        state: absent


    ##########################################
    # STEP 6 — ENABLE OVERLAY & BR_NETFILTER
    ##########################################
    - name: Create modules file
      ansible.builtin.copy:
        dest: /etc/modules-load.d/k8s.conf
        content: |
          overlay
          br_netfilter
        mode: '0644'

    - name: Load overlay module
      community.general.modprobe:
        name: overlay
        state: present

    - name: Load br_netfilter module
      community.general.modprobe:
        name: br_netfilter
        state: present


    ##########################################
    # STEP 7 — ENABLE SYSCTL SETTINGS
    ##########################################
    - name: Enable sysctl params
      ansible.builtin.copy:
        dest: /etc/sysctl.d/k8s.conf
        content: |
          net.bridge.bridge-nf-call-iptables = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.ipv4.ip_forward = 1
        mode: '0644'
        owner: root
        group: root

    - name: Reload sysctl
      ansible.builtin.command: sysctl --system


    ##########################################
    # STEP 8 — MANAGE /etc/hosts
    ##########################################
    - name: Update /etc/hosts
      ansible.builtin.blockinfile:
        path: /etc/hosts
        block: |
          192.168.56.100 ctrl
          192.168.56.101 node-1
          192.168.56.102 node-2
        create: yes

    - name: Configure /etc/hosts for cluster node name resolution
      copy:
        src: "{{ playbook_dir }}/ansible/hosts"
        dest: /etc/hosts
        owner: root
        group: root
        mode: "0644"


    ##########################################
    # STEP 9 — ADD KUBERNETES REPOSITORY 
    ##########################################
    - name: Ensure keyrings directory exists
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Kubernetes GPG key
      ansible.builtin.get_url:
        url: https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key
        dest: /etc/apt/keyrings/kubernetes-release.key
        mode: '0644'

    - name: Convert key to GPG format
      ansible.builtin.command:
        cmd: >
          gpg --dearmor -o /etc/apt/keyrings/kubernetes.gpg
          /etc/apt/keyrings/kubernetes-release.key
      args:
        creates: /etc/apt/keyrings/kubernetes.gpg

    - name: Add Kubernetes apt repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/kubernetes.gpg] https://pkgs.k8s.io/core:/stable:/v1.32/deb/ /"
        state: present
        filename: kubernetes

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

        
    ##########################################
    # STEP 10 — INSTALL K8S TOOLS
    ##########################################
    - name: Install containerd and runc
      ansible.builtin.apt:
        name:
          - containerd=1.7.28-0ubuntu1~24.04.1
          - runc=1.3.3-0ubuntu1~24.04.3
        state: present
        update_cache: yes

    - name: Install kubeadm, kubelet, and kubectl
      ansible.builtin.apt:
        name:
          - kubeadm=1.32.4-1.1
          - kubelet=1.32.4-1.1
          - kubectl=1.32.4-1.1
        state: present
        update_cache: yes
        
    ##########################################
    # STEP 11 — CONFIGURE CONTAINERD
    ##########################################

    - name: Ensure containerd directory exists
      ansible.builtin.file:
        path: /etc/containerd
        state: directory
        mode: '0755'

    - name: Generate default containerd config
      ansible.builtin.shell: containerd config default > /etc/containerd/config.toml
      args:
        creates: /etc/containerd/config.toml

    - name: Disable AppArmor in containerd
      ansible.builtin.lineinfile:
        path: /etc/containerd/config.toml
        regexp: 'disable_apparmor ='
        line: '    disable_apparmor = true'

    - name: Update sandbox image
      ansible.builtin.lineinfile:
        path: /etc/containerd/config.toml
        regexp: 'sandbox_image ='
        line: '    sandbox_image = "registry.k8s.io/pause:3.10"'

    - name: Enable SystemdCgroup for runc
      ansible.builtin.lineinfile:
        path: /etc/containerd/config.toml
        regexp: 'SystemdCgroup ='
        line: '            SystemdCgroup = true'

    - name: Restart containerd
      ansible.builtin.service:
        name: containerd
        state: restarted

    ##########################################
    # STEP 12 — ENABLE AND START KUBELET
    ##########################################
    - name: Enable kubelet service
      ansible.builtin.service:
        name: kubelet
        enabled: yes

    - name: Start kubelet service
      ansible.builtin.service:
        name: kubelet
        state: started

        
