apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sms-checker-app
  labels:
    release: myprom       
spec:
  selector:
    matchLabels:
      app: sms-checker-app
  endpoints:
    - port: http
      path: /metrics
      interval: 15s

