apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sms-checker-app
  namespace: {{ .Release.Namespace }}
  labels:
    release: myprom
spec:
  selector:
    matchLabels:
      app: sms-checker-app
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
