apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: model-service
  namespace: {{ .Release.Namespace }}
  labels:
    release: myprom
spec:
  selector:
    matchLabels:
      app: model-service
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
