apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: model-service
  labels:
    release: myprom       
spec:
  selector:
    matchLabels:
      app: model-service
  endpoints:
    - port: http
      path: /metrics
      interval: 15s

