apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-service-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.modelService.storage.size }}
