apiVersion: v1
kind: Service
metadata:
  name: model-service
  labels:
    app: model-service 
spec:
  selector:
    app: model-service
  ports:
    - name: http  
      port: {{ .Values.modelService.port }}
      targetPort: {{ .Values.modelService.port }}
      protocol: TCP
