apiVersion: v1
kind: Secret
metadata:
  name: sms-checker-secret
type: Opaque
stringData:
  # Placeholder sensitive values
  SMTP_USER: "your-smtp-user"
  SMTP_PASSWORD: "your-smtp-password"
  API_KEY: "your-api-key"
